### ISSUE TITLE
ltm data-group

### ISSUE THREAD

**Issue by jpockele** [AhmedThabet/f5py-doc#1]
ltm data-group is not available. Will this be included in the future?

**Comment by AhmedThabet** [comment]
I started with the most used objects & planning to gradually add the rest going forward.
Will prioritise the addition of ltm data-group in the near future.

**Comment by jpockele** [comment]
Hello Ahmed,

Thank you for your answer. If there is anything I could do to contribute?

Jannes

Van: AhmedThabet ***@***.***>
Verzonden: zaterdag 3 juni 2023 0:01
Aan: AhmedThabet/f5py-doc ***@***.***>
CC: Jannes Pockelé ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AhmedThabet/f5py-doc] ltm data-group (Issue #1)


WAARSCHUWING: DIT IS EEN EXTERNE MAIL

Deze mail komt van buiten onze organisatie. Kijk eerst of je het mailadres en de afzender herkent en/of vertrouwt. Doe dat voor je bijlagen opent of links aanklikt. Zo houden we onze organisatie veiliger voor phishing.

I started with the most used objects & planning to gradually add the rest going forward.
Will prioritise the addition of ltm data-group in the near future.

**Comment by AhmedThabet** [comment]
Thanks Jannes, I've made some progress already and hoping I can publish the new version within the coming month or so

**Comment by jpockele** [comment]
Super!

I used a work-around to get the data, but I think many others will thank you 😊

Jannes

Van: AhmedThabet ***@***.***>
Verzonden: dinsdag 6 februari 2024 22:52
Aan: AhmedThabet/f5py-doc ***@***.***>
CC: Jannes Pockelé ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AhmedThabet/f5py-doc] ltm data-group (Issue #1)

U ontvangt niet vaak e-mail van ***@***.******@***.***>. Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

WAARSCHUWING: DIT IS EEN EXTERNE MAIL

Deze mail komt van buiten onze organisatie. Kijk eerst of je het mailadres en de afzender herkent en/of vertrouwt. Doe dat voor je bijlagen opent of links aanklikt. Zo houden we onze organisatie veiliger voor phishing.

Thanks Jannes, I've made some progress already and hoping I can publish the new version within the coming month or so

**Comment by AhmedThabet** [comment]
Good to know so :)
By the way, I've added the data group parsing & it's already used within this wasm portal `https://ipvx.me/f5`.
This will be added to the next version of f5py lib

**Comment by jpockele** [comment]
You are the best!

Jannes

Van: AhmedThabet ***@***.***>
Verzonden: vrijdag 23 februari 2024 1:13
Aan: AhmedThabet/f5py-doc ***@***.***>
CC: Jannes Pockelé ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AhmedThabet/f5py-doc] ltm data-group (Issue #1)

U ontvangt niet vaak e-mail van ***@***.******@***.***>. Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

WAARSCHUWING: DIT IS EEN EXTERNE MAIL

Deze mail komt van buiten onze organisatie. Kijk eerst of je het mailadres en de afzender herkent en/of vertrouwt. Doe dat voor je bijlagen opent of links aanklikt. Zo houden we onze organisatie veiliger voor phishing.

Good to know so :)
By the way, I've added the data group parsing & it's already used within this wasm portal https://ipvx.me/f5.
This will be added to the next version of f5py lib

**Comment by AhmedThabet** [comment]
Thanks a lot for your nice words.
data-group parsing is now pushed to pypi with version 0.3.0
