### ISSUE TITLE
Wheel versions on not suported past MacOS 11 (looking for 14 support currently)

### ISSUE THREAD

**Issue by samualblair** [AhmedThabet/f5py-doc#3]
Wheel versions on not supported past MacOS 11.
I'm looking for (or hoping for) MacOS 14 (arm) now and not able to get the MacOS 11 arm variation working.
Perhaps updated binaries can be published to pipi.org?

Also shout-out, the wasm implementation on ipvx.me looks great, very useful!
Just hoping to have a local and python ready version.

**Comment by AhmedThabet** [comment]
Sure, I'll do this with the next release. As I still need to setup the mac dev emulated environment :|

I'm glad you found the wasm implementation useful & really appreciate your feedback.

**Comment by AhmedThabet** [comment]
Version 0.3.0 is now pushed to pypi, please give it a try and keep me aligned with the results.
Thanks

**Comment by samualblair** [comment]
I see the new version and can confirm this works for me now, thank you for your quick updates!
